### ISSUE TITLE
Index and time tracking of the payload and attack respectively [New Feature]

### ISSUE THREAD

**Issue by cimplesid** [TheBinitGhimire/WHOISxss#1]
I would be glad to send PR if you are willing to add the feature

**Comment by cimplesid** [comment]
[#2 ](https://github.com/TheBinitGhimire/WHOISxss/pull/2)

**Comment by TheBinitGhimire** [comment]
Hello @cimplesid,

Thank You for opening this issue regarding a feature inclusion in **WHOISxss**!

I just went through your [commit](https://github.com/TheBinitGhimire/WHOISxss/tree/283ead61c12f44d189e6c96464b9f53bbf987ce7), and decided to merge it into the **[master](https://github.com/TheBinitGhimire/WHOISxss/tree/master)** branch of **WHOISxss**, and you should now be able to see yourself included in the **[Contributors](https://github.com/TheBinitGhimire/WHOISxss#contributors)** section both in the repository and the **[README.md](https://github.com/TheBinitGhimire/WHOISxss/blob/master/README.md)** file.

Again, I would like to thank you for contributing to the development of **WHOISxss**!

Thanks,
@TheBinitGhimire
